### ISSUE TITLE
bot update?

### ISSUE THREAD

**Issue by cookins** [FoRoKo1o/DiscordBot#1]
hey there. some months before bot was working fabulous. now it sends only messages to ig chat, but nothing back to discord. maybe there some changes happened in API and bot need update?

**Comment by FoRoKo1o** [comment]
I have tested bot on my clan and server and it's still working fine, but there were few errors like this in past caused probably by the hosting I was using (free version of Replit). 
Simply restart bot on Replit and it should be working fine.
