### ISSUE TITLE
Discord names

### ISSUE THREAD

**Issue by cookins** [FoRoKo1o/DiscordBot#2]
Hey again.
I wanted to suggest nice feature. Bot takes names from discord main accounts and that names mentioned ig chat. It's best, to bot mention their names on current discord server, but not from main discord accounts. It's more handy to figure who is who, specially, when every got plenty of discord servers, with different nicknames.

**Comment by FoRoKo1o** [comment]
Make a change in index.js
from:
`  const username = message.author.username;`
to:
`  const username = message.member.nickname || message.author.username;`
